name: Check GitHub Secrets

on:
  workflow_dispatch:  # Позволяет запускать процесс вручную

jobs:
  check-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print secrets
        env:
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          S3_KEY_ID: ${{ secrets.S3_KEY_ID }}
          S3_APPLICATION_KEY: ${{ secrets.S3_APPLICATION_KEY }}
        run: |
          echo "S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}"
          echo "S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}"
          echo "S3_KEY_ID: ${S3_KEY_ID:0:4}****"
          echo "S3_APPLICATION_KEY: ${S3_APPLICATION_KEY//?/*}"
