name: Check Secrets and Run Script

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install boto3

      - name: Run B2 script
        env:
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          S3_KEY_ID: ${{ secrets.S3_KEY_ID }}
          S3_APPLICATION_KEY: ${{ secrets.S3_APPLICATION_KEY }}
        run: python scripts/B2_Content_Download.py

      - name: Ensure directories and list contents
        run: |
          mkdir -p a1/data/downloaded
          mkdir -p a1/logs
          echo "Contents of downloaded:"
          ls -la a1/data/downloaded
          echo "Contents of logs:"
          ls -la a1/logs

      - name: Upload downloaded files
        uses: actions/upload-artifact@v3
        with:
          name: downloaded-files
          path: a1/data/downloaded/

      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: a1/logs/
