---
name: B2 Content Download

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install b2sdk

      - name: Debug Repository Structure
        run: |
          echo "Current directory: $(pwd)"
          ls -R
        shell: bash

      - name: Ensure downloaded directory exists
        run: mkdir -p ${{ github.workspace }}/data/downloaded && touch ${{ github.workspace }}/data/downloaded/.gitkeep
        shell: bash

      - name: Run B2_Content_Download.py
        env:
          S3_KEY_ID: ${{ secrets.S3_KEY_ID }}
          S3_APPLICATION_KEY: ${{ secrets.S3_APPLICATION_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python scripts/B2_Content_Download.py

      - name: Debug Проверка имен файлов перед mv
        run: |
          echo "Файлы перед перемещением:"
          find /home/runner/work/a1/a1/data/downloaded/ -type f || echo "❌ Нет файлов для перемещения!"
        shell: bash

      - name: Move downloaded files to workspace
        run: |
          find /home/runner/work/a1/a1/data/downloaded/ -type f -exec mv {} ${{ github.workspace }}/data/downloaded/ \;
        shell: bash

      - name: Debug List downloaded files
        run: |
          echo "Listing files in downloaded folder:"
          ls -R ${{ github.workspace }}/data/downloaded/
        shell: bash

      - name: Upload downloaded files as artifact
        uses: actions/upload-artifact@v3
        with:
          name: downloaded_files
          path: ${{ github.workspace }}/data/downloaded/
