name: Schedule Telegram Publication

on:
  schedule:
    - cron: "0 7 * * *"  # Запуск в 07:00 UTC (10:00 МСК)
  workflow_dispatch:  # Возможность ручного запуска через GitHub

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install requests boto3 python-dotenv b2sdk
          pip list  # Вывести список установленных пакетов для отладки

      - name: Debug environment variables
        run: |
          echo "S3_KEY_ID=$S3_KEY_ID"
          echo "S3_APPLICATION_KEY=$S3_APPLICATION_KEY"
          echo "S3_ENDPOINT=$S3_ENDPOINT"
          echo "S3_BUCKET_NAME=$S3_BUCKET_NAME"

      - name: Debug directory structure
        run: |
          echo "Checking existing directories..."
          find . -type d | sort

      - name: Create downloaded directory
        run: mkdir -p data/downloaded

      - name: Run module2_publication.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          S3_KEY_ID: ${{ secrets.S3_KEY_ID }}
          S3_APPLICATION_KEY: ${{ secrets.S3_APPLICATION_KEY }}
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export S3_KEY_ID=${{ secrets.S3_KEY_ID }}
          export S3_APPLICATION_KEY=${{ secrets.S3_APPLICATION_KEY }}
          export S3_ENDPOINT=${{ secrets.S3_ENDPOINT }}
          export S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}
          export GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
          echo "S3_KEY_ID = $S3_KEY_ID"
          echo "S3_APPLICATION_KEY = $S3_APPLICATION_KEY"
          echo "S3_ENDPOINT = $S3_ENDPOINT"
          echo "S3_BUCKET_NAME = $S3_BUCKET_NAME"
          echo "GH_TOKEN = $GH_TOKEN"
          python scripts/module2_publication.py

      - name: Archive downloaded file
        run: |
          zip -r downloaded_files.zip /home/runner/work/a1/a1/data/downloaded/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: downloaded_files
          path: /home/runner/work/a1/a1/data/downloaded/