name: Test B2 Access

on:
  workflow_dispatch:  # Позволяет запускать процесс вручную через интерфейс GitHub

jobs:
  test-b2-access:
    runs-on: ubuntu-latest

    steps:
      # Проверка кода из репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Установка Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Установка зависимостей
      - name: Install dependencies
        run: pip install boto3

      # Запуск тестового скрипта
      - name: Run B2 access test
        env:
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}  # Секреты для безопасного хранения
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          S3_KEY_ID: ${{ secrets.S3_KEY_ID }}
          S3_APPLICATION_KEY: ${{ secrets.S3_APPLICATION_KEY }}
        run: |
          python <<EOF
          import boto3
          from botocore.exceptions import NoCredentialsError, PartialCredentialsError

          # Конфигурация
          ENDPOINT = "${{ secrets.S3_ENDPOINT }}"
          BUCKET_NAME = "${{ secrets.S3_BUCKET_NAME }}"
          KEY_ID = "${{ secrets.S3_KEY_ID }}"
          APPLICATION_KEY = "${{ secrets.S3_APPLICATION_KEY }}"

          def test_b2_connection():
              try:
                  # Создание клиента S3 с параметрами Backblaze B2
                  s3_client = boto3.client(
                      's3',
                      endpoint_url=ENDPOINT,
                      aws_access_key_id=KEY_ID,
                      aws_secret_access_key=APPLICATION_KEY
                  )

                  # Список объектов в бакете
                  response = s3_client.list_objects_v2(Bucket=BUCKET_NAME)

                  if 'Contents' in response:
                      print("Объекты в бакете:")
                      for obj in response['Contents']:
                          print(f" - {obj['Key']}")
                  else:
                      print("Бакет пуст или отсутствуют права на доступ.")

              except NoCredentialsError:
                  print("Ошибка: неверные или отсутствующие учетные данные.")
              except PartialCredentialsError:
                  print("Ошибка: указаны не все учетные данные.")
              except Exception as e:
                  print(f"Произошла ошибка: {e}")

          if __name__ == "__main__":
              test_b2_connection()
          EOF
